language: python
python:
  - "2.7"
  env:
    - DJANGO_VERSION=1.5

#Command to install dependencies
install: "pip install -r requirements.txt"

script:
  - cp DigOp/local_settings.py.template DigOp/local_settings.py
  - python ui/manage.py test ui

branches:
  only:
      - master

notifications:
  email:
    - sgilani@email.gwu.edu
