##################################################
# file: WSBarcodePages_client.py
# 
# client stubs generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#     C:\Python27\scripts\wsdl2py-script.py http://128.164.212.164:8080/BarcodeService/WSBarcodePages?wsdl
# 
##################################################

from WSBarcodePages_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
from ZSI.schema import GED, GTD
import ZSI

# Locator
class WSBarcodePagesLocator:
    WSBarcodePagesPort_address = "http://128.164.212.164:8080/BarcodeService/WSBarcodePages"
    def getWSBarcodePagesPortAddress(self):
        return WSBarcodePagesLocator.WSBarcodePagesPort_address
    def getWSBarcodePagesPort(self, url=None, **kw):
        return WSBarcodePagesPortBindingSOAP(url or WSBarcodePagesLocator.WSBarcodePagesPort_address, **kw)

# Methods
class WSBarcodePagesPortBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: getPages
    def getPages(self, request, **kw):
        if isinstance(request, getPages) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="", **kw)
        # no output wsaction
        response = self.binding.Receive(getPagesResponse.typecode)
        return response

getPages = GED("http://WSBarcode/", "getPages").pyclass

getPagesResponse = GED("http://WSBarcode/", "getPagesResponse").pyclass
