##################################################
# file: WSBarcodePages_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      C:\Python27\scripts\wsdl2py-script.py http://128.164.212.164:8080/BarcodeService/WSBarcodePages?wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from WSBarcodePages_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
getPages = GED("http://WSBarcode/", "getPages").pyclass

getPagesResponse = GED("http://WSBarcode/", "getPagesResponse").pyclass


# Service Skeletons
class WSBarcodePages(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/BarcodeService/WSBarcodePages', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_getPages(self, ps, **kw):
        request = ps.Parse(getPages.typecode)
        return request,getPagesResponse()

    soapAction[''] = 'soap_getPages'
    root[(getPages.typecode.nspname,getPages.typecode.pname)] = 'soap_getPages'

